-- ============================================================================
-- 163-backup-schema.sql  -  the backup carries the shape as well as the data.
--
-- The gap: a zip full of records is useless if there is no Orbit left to put
-- them into. The data was portable; the SHAPE it goes back into lived only in
-- the source repository, so recovery quietly depended on that repository still
-- existing and on somebody knowing it was needed.
--
-- backup_schema_sql() writes the whole public schema out as SQL, read from the
-- catalogue at the moment the backup is taken: every table, constraint, index,
-- function, trigger, view, and every row-level security policy. Postgres hands
-- back exact definitions for most of it, so this is a transcription rather
-- than a reconstruction.
--
-- With schema.sql in the zip beside data.json and the files, the backup is the
-- whole thing: run the SQL into an empty database, restore the data, done.
-- ============================================================================

create or replace function public.backup_schema_sql()
returns text
language plpgsql
security definer
set search_path = public
as $fn$
declare
  out text := '';
  r record;
  cols text;
begin
  out := out || '-- Orbit schema, written by the backup on ' || to_char(now(), 'YYYY-MM-DD HH24:MI') || E'\n';
  out := out || '-- Run this into an EMPTY database, then restore the data beside it.' || E'\n';
  out := out || '-- Order does not matter to function bodies: checking is turned off for the run.' || E'\n\n';
  out := out || 'set check_function_bodies = off;' || E'\n';
  out := out || 'create schema if not exists public;' || E'\n\n';

  -- extensions this database actually uses
  out := out || E'-- ---- extensions ----\n';
  for r in select extname, nspname from pg_extension e join pg_namespace n on n.oid = e.extnamespace
            where extname not in ('plpgsql') order by extname loop
    out := out || 'create extension if not exists ' || quote_ident(r.extname) || ' with schema ' || quote_ident(r.nspname) || ';' || E'\n';
  end loop;

  -- enums and domains
  out := out || E'\n-- ---- types ----\n';
  for r in select t.typname,
                  string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder) labels
             from pg_type t join pg_enum e on e.enumtypid = t.oid
             join pg_namespace n on n.oid = t.typnamespace and n.nspname = 'public'
            group by t.typname order by t.typname loop
    out := out || 'do $do$ begin create type public.' || quote_ident(r.typname) || ' as enum (' || r.labels || '); exception when duplicate_object then null; end $do$;' || E'\n';
  end loop;

  -- sequences that are not owned by an identity column
  out := out || E'\n-- ---- sequences ----\n';
  for r in select sequencename from pg_sequences where schemaname = 'public' order by sequencename loop
    out := out || 'create sequence if not exists public.' || quote_ident(r.sequencename) || ';' || E'\n';
  end loop;

  -- tables, columns only; every constraint comes later so order cannot bite
  out := out || E'\n-- ---- tables ----\n';
  for r in select c.relname as tbl
             from pg_class c join pg_namespace n on n.oid = c.relnamespace
            where n.nspname = 'public' and c.relkind = 'r' order by c.relname loop
    -- a generated column is not a default and an identity column is not either;
    -- writing them out as defaults produces SQL that will not run
    select string_agg(
             '  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
             || case
                  when a.attgenerated = 's' then ' generated always as (' || pg_get_expr(ad.adbin, ad.adrelid) || ') stored'
                  when a.attidentity = 'a' then ' generated always as identity'
                  when a.attidentity = 'd' then ' generated by default as identity'
                  else coalesce(' default ' || pg_get_expr(ad.adbin, ad.adrelid), '')
                end
             || case when a.attnotnull and a.attgenerated <> 's' then ' not null' else '' end, E',\n' order by a.attnum)
      into cols
      from pg_attribute a
      left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
      join pg_class c on c.oid = a.attrelid
      join pg_namespace n on n.oid = c.relnamespace and n.nspname = 'public'
     where c.relname = r.tbl and a.attnum > 0 and not a.attisdropped;
    out := out || 'create table if not exists public.' || quote_ident(r.tbl) || ' (' || E'\n' || cols || E'\n);\n';
  end loop;

  -- functions before triggers and policies, because both call them
  out := out || E'\n-- ---- functions ----\n';
  for r in select p.oid, p.proname from pg_proc p
             join pg_namespace n on n.oid = p.pronamespace and n.nspname = 'public'
            where p.prokind in ('f', 'p') order by p.proname loop
    begin
      out := out || pg_get_functiondef(r.oid) || ';' || E'\n\n';
    exception when others then
      out := out || '-- could not write function ' || r.proname || ': ' || SQLERRM || E'\n';
    end;
  end loop;

  -- primary keys, uniques and checks, then foreign keys once every table exists
  out := out || E'\n-- ---- keys and checks ----\n';
  for r in select c.conname, cl.relname tbl, pg_get_constraintdef(c.oid) def, c.contype
             from pg_constraint c
             join pg_class cl on cl.oid = c.conrelid
             join pg_namespace n on n.oid = cl.relnamespace and n.nspname = 'public'
            where c.contype in ('p', 'u', 'c') order by c.contype, cl.relname, c.conname loop
    out := out || 'alter table public.' || quote_ident(r.tbl) || ' add constraint ' || quote_ident(r.conname) || ' ' || r.def || ';' || E'\n';
  end loop;

  out := out || E'\n-- ---- foreign keys ----\n';
  for r in select c.conname, cl.relname tbl, pg_get_constraintdef(c.oid) def
             from pg_constraint c
             join pg_class cl on cl.oid = c.conrelid
             join pg_namespace n on n.oid = cl.relnamespace and n.nspname = 'public'
            where c.contype = 'f' order by cl.relname, c.conname loop
    out := out || 'alter table public.' || quote_ident(r.tbl) || ' add constraint ' || quote_ident(r.conname) || ' ' || r.def || ';' || E'\n';
  end loop;

  out := out || E'\n-- ---- indexes ----\n';
  for r in select indexname, indexdef from pg_indexes
            where schemaname = 'public'
              and indexname not in (select conname from pg_constraint where contype in ('p', 'u'))
            order by tablename, indexname loop
    out := out || replace(r.indexdef, 'CREATE INDEX', 'CREATE INDEX IF NOT EXISTS') || ';' || E'\n';
  end loop;

  out := out || E'\n-- ---- views ----\n';
  for r in select viewname, definition from pg_views where schemaname = 'public' order by viewname loop
    out := out || 'create or replace view public.' || quote_ident(r.viewname) || ' as ' || E'\n' || r.definition || E'\n';
  end loop;

  out := out || E'\n-- ---- triggers ----\n';
  for r in select t.oid, t.tgname from pg_trigger t
             join pg_class c on c.oid = t.tgrelid
             join pg_namespace n on n.oid = c.relnamespace and n.nspname = 'public'
            where not t.tgisinternal order by t.tgname loop
    out := out || pg_get_triggerdef(r.oid) || ';' || E'\n';
  end loop;

  -- the part a half-written schema gets wrong and nobody notices until the
  -- wrong company can read the wrong data
  out := out || E'\n-- ---- row level security ----\n';
  for r in select c.relname tbl from pg_class c
             join pg_namespace n on n.oid = c.relnamespace and n.nspname = 'public'
            where c.relkind = 'r' and c.relrowsecurity order by c.relname loop
    out := out || 'alter table public.' || quote_ident(r.tbl) || ' enable row level security;' || E'\n';
  end loop;
  for r in select schemaname, tablename, policyname, permissive, roles, cmd, qual, with_check
             from pg_policies where schemaname = 'public' order by tablename, policyname loop
    out := out || 'drop policy if exists ' || quote_ident(r.policyname) || ' on public.' || quote_ident(r.tablename) || ';' || E'\n';
    out := out || 'create policy ' || quote_ident(r.policyname) || ' on public.' || quote_ident(r.tablename)
                || ' as ' || lower(r.permissive) || ' for ' || lower(r.cmd)
                || ' to ' || array_to_string(r.roles, ', ')
                || coalesce(' using (' || r.qual || ')', '')
                || coalesce(' with check (' || r.with_check || ')', '') || ';' || E'\n';
  end loop;

  out := out || E'\n-- ---- grants ----\n';
  out := out || 'grant usage on schema public to anon, authenticated, service_role;' || E'\n';
  out := out || 'grant all on all tables in schema public to anon, authenticated, service_role;' || E'\n';
  out := out || 'grant all on all sequences in schema public to anon, authenticated, service_role;' || E'\n';
  out := out || 'grant all on all functions in schema public to anon, authenticated, service_role;' || E'\n';
  out := out || E'\nset check_function_bodies = on;\n';
  out := out || '-- end of schema' || E'\n';
  return out;
end $fn$;
grant execute on function public.backup_schema_sql() to authenticated;

-- ---------------------------------------------------------------------------
-- The other half of the gap. A restore checked that the caller belonged to the
-- organisation named in the FILE, which is exactly the thing that no longer
-- exists after a disaster. If that organisation is not in this database, this
-- is a rebuild, and the restore goes into the caller's own.
-- ---------------------------------------------------------------------------
create or replace function public.backup_target_org(p_file_org uuid)
returns uuid
language plpgsql
stable
security definer
set search_path = public
as $fn$
declare mine uuid;
begin
  if p_file_org is not null and exists (select 1 from public.orgs o where o.id = p_file_org) then
    return p_file_org;
  end if;
  select m.org_id into mine from public.org_members m
   where m.user_id = auth.uid() and m.role in ('owner', 'admin', 'accountant')
   order by m.created_at nulls last limit 1;
  return mine;
end $fn$;
grant execute on function public.backup_target_org(uuid) to authenticated;
