-- ============================================================================
-- 191-role-write-gates.sql  -  every table checks the role's level in its app.
--
-- The write rules on these tables let any active member whose role writes
-- somewhere save (can_write_company, from 190). This adds a second, restrictive
-- rule to each of them, which must also pass: inserting and changing a row needs
-- Own, Work or Manage in one of the apps that record it, and deleting needs the
-- same, or Manage for records that other records depend on (accounts, products,
-- contacts, projects, warehouses and each app's configuration).
--
-- A table written by several apps lists all of them: a stock movement is saved
-- by Inventory, Purchase, Sales, Manufacturing and the till, and a journal entry
-- by every app that posts. Posting itself stays in the functions that post.
--
-- Salaries: contracts, payslips and payroll runs are only readable by a role that
-- sees salaries, and a person can always read their own.
-- Nothing here touches reading any other table.
-- ============================================================================

do $gates$
declare g record; fn text;
begin
  for g in select * from (values
    ('accounts', '{accounting}'::text[], 'M', 'company_id'),
    ('aggregator_accounts', '{kitchen,pos}'::text[], 'M', 'company_id'),
    ('aggregator_disputes', '{kitchen,pos}'::text[], 'W', 'company_id'),
    ('aggregator_orders', '{kitchen,pos}'::text[], 'W', 'company_id'),
    ('aggregator_payouts', '{kitchen,pos}'::text[], 'W', 'company_id'),
    ('applicants', '{recruitment,employees}'::text[], 'W', 'company_id'),
    ('appraisals', '{employees}'::text[], 'W', 'company_id'),
    ('approval_rules', '{settings,accounting}'::text[], 'M', 'company_id'),
    ('approved_suppliers', '{purchase}'::text[], 'M', 'company_id'),
    ('appt_appointments', '{appoint}'::text[], 'W', 'company_id'),
    ('appt_availability', '{appoint}'::text[], 'W', 'company_id'),
    ('appt_files', '{appoint}'::text[], 'W', 'company_id'),
    ('appt_notes', '{appoint}'::text[], 'W', 'company_id'),
    ('appt_services', '{appoint}'::text[], 'M', 'company_id'),
    ('appt_settings', '{appoint}'::text[], 'M', 'company_id'),
    ('ar_followups', '{accounting,sales}'::text[], 'W', 'company_id'),
    ('articles', '{knowledge,website}'::text[], 'W', 'company_id'),
    ('asset_lines', '{accounting}'::text[], 'W', 'company_id'),
    ('assets', '{accounting}'::text[], 'M', 'company_id'),
    ('automation_rules', '{settings}'::text[], 'M', 'company_id'),
    ('backup_settings', '{settings}'::text[], 'M', 'company_id'),
    ('backups', '{settings}'::text[], 'M', 'company_id'),
    ('bank_statement_lines', '{accounting}'::text[], 'W', 'company_id'),
    ('bank_statements', '{accounting}'::text[], 'W', 'company_id'),
    ('bom_lines', '{manufacturing}'::text[], 'W', 'company_id'),
    ('boms', '{manufacturing}'::text[], 'M', 'company_id'),
    ('books', '{accounting}'::text[], 'M', 'company_id'),
    ('brands', '{inventory}'::text[], 'M', 'company_id'),
    ('budget_lines', '{accounting,projects}'::text[], 'W', 'company_id'),
    ('budgets', '{accounting,projects}'::text[], 'M', 'company_id'),
    ('calendar_events', '{calendar,crm,projects,site,events,appoint,employees,service,plot,sales}'::text[], 'W', 'company_id'),
    ('cash_accounts', '{counter}'::text[], 'M', 'company_id'),
    ('cash_counts', '{counter}'::text[], 'W', 'company_id'),
    ('cash_drops', '{counter,pos,kitchen}'::text[], 'W', 'company_id'),
    ('cash_handovers', '{counter}'::text[], 'W', 'company_id'),
    ('cash_movements', '{counter}'::text[], 'W', 'company_id'),
    ('certifications', '{employees}'::text[], 'W', 'company_id'),
    ('checklist_results', '{kitchen,site,service,pos}'::text[], 'W', 'company_id'),
    ('checklist_runs', '{kitchen,site,service,pos}'::text[], 'W', 'company_id'),
    ('checklist_template_items', '{kitchen,site,service,pos}'::text[], 'W', 'company_id'),
    ('checklist_templates', '{kitchen,site,service,pos}'::text[], 'M', 'company_id'),
    ('companies', '{settings,accounting}'::text[], 'M', 'id'),
    ('compliance_documents', '{kitchen,site,documents,pos}'::text[], 'W', 'company_id'),
    ('consolidation_adjustments', '{accounting}'::text[], 'W', 'company_id'),
    ('consolidation_group_companies', '{accounting}'::text[], 'W', 'company_id'),
    ('consolidation_runs', '{accounting}'::text[], 'W', '(select g.company_id from public.consolidation_group_companies g where g.group_id = consolidation_runs.group_id and public.can_write_app(g.company_id, array[''accounting'']) limit 1)'),
    ('contact_tags', '{contacts}'::text[], 'M', 'company_id'),
    ('cost_codes', '{projects,accounting,site}'::text[], 'M', 'company_id'),
    ('crm_activities', '{crm,sales}'::text[], 'W', 'company_id'),
    ('crm_lead_contacts', '{crm,sales}'::text[], 'W', 'company_id'),
    ('crm_leads', '{crm,sales}'::text[], 'W', 'company_id'),
    ('crm_stages', '{crm}'::text[], 'M', 'company_id'),
    ('custom_field_defs', '{settings}'::text[], 'M', 'company_id'),
    ('deliveries', '{kitchen,pos,sales,inventory}'::text[], 'W', 'company_id'),
    ('delivery_methods', '{inventory,sales}'::text[], 'M', 'company_id'),
    ('delivery_note_lines', '{inventory,purchase,sales,manufacturing,projects,site,pos,kitchen,service}'::text[], 'W', '(select n.company_id from public.delivery_notes n where n.id = note_id)'),
    ('delivery_notes', '{inventory,sales,site,projects}'::text[], 'W', 'company_id'),
    ('delivery_zones', '{kitchen,pos}'::text[], 'M', 'company_id'),
    ('dies', '{manufacturing}'::text[], 'M', 'company_id'),
    ('drawing_revisions', '{documents,projects,site}'::text[], 'W', 'company_id'),
    ('drawings', '{documents,projects,site}'::text[], 'W', 'company_id'),
    ('einvoice_docs', '{accounting,sales}'::text[], 'W', 'company_id'),
    ('employee_availability', '{employees,kitchen,appoint,service}'::text[], 'W', 'company_id'),
    ('employee_skills', '{employees}'::text[], 'W', 'company_id'),
    ('equipment', '{manufacturing,service,site}'::text[], 'M', 'company_id'),
    ('equipment_events', '{manufacturing,service,site}'::text[], 'W', 'company_id'),
    ('event_events', '{events}'::text[], 'W', 'company_id'),
    ('feedback', '{events,kitchen,pos,service}'::text[], 'W', 'company_id'),
    ('fiscal_periods', '{accounting}'::text[], 'M', 'company_id'),
    ('fiscal_years', '{accounting}'::text[], 'M', 'company_id'),
    ('followup_levels', '{accounting}'::text[], 'M', 'company_id'),
    ('franchise_pipeline', '{kitchen,pos}'::text[], 'W', 'company_id'),
    ('franchise_sales_reports', '{kitchen,pos}'::text[], 'W', 'company_id'),
    ('franchisees', '{kitchen,pos}'::text[], 'M', 'company_id'),
    ('green_lots', '{kitchen,manufacturing,inventory}'::text[], 'W', 'company_id'),
    ('grinder_logs', '{kitchen,manufacturing}'::text[], 'W', 'company_id'),
    ('hr_attendances', '{employees}'::text[], 'W', 'company_id'),
    ('hr_contracts', '{employees}'::text[], 'W', 'company_id'),
    ('hr_departments', '{employees}'::text[], 'M', 'company_id'),
    ('hr_employees', '{employees,recruitment}'::text[], 'M', 'company_id'),
    ('hr_expenses', '{employees}'::text[], 'W', 'company_id'),
    ('hr_jobs', '{employees,recruitment}'::text[], 'M', 'company_id'),
    ('hr_leave_allocations', '{employees}'::text[], 'W', 'company_id'),
    ('hr_leaves', '{employees}'::text[], 'W', 'company_id'),
    ('hr_onboarding', '{employees,recruitment}'::text[], 'W', 'company_id'),
    ('hr_payslip_lines', '{employees}'::text[], 'W', 'company_id'),
    ('hr_payslip_runs', '{employees}'::text[], 'W', 'company_id'),
    ('hr_payslips', '{employees}'::text[], 'W', 'company_id'),
    ('hr_roster', '{employees,kitchen}'::text[], 'W', 'company_id'),
    ('hr_salary_heads', '{employees}'::text[], 'M', 'company_id'),
    ('hr_salary_structures', '{employees}'::text[], 'M', 'company_id'),
    ('hr_shifts', '{employees,kitchen}'::text[], 'W', 'company_id'),
    ('inspection_items', '{site,manufacturing,projects}'::text[], 'W', 'company_id'),
    ('inspection_template_items', '{site,manufacturing,projects}'::text[], 'W', 'company_id'),
    ('inspection_templates', '{site,manufacturing,projects}'::text[], 'M', 'company_id'),
    ('inspections', '{site,manufacturing,projects}'::text[], 'W', 'company_id'),
    ('install_jobs', '{site,projects}'::text[], 'W', 'company_id'),
    ('install_logs', '{site,projects}'::text[], 'W', 'company_id'),
    ('invoice_lines', '{accounting,counter,sales,purchase,inventory,employees,projects,site,manufacturing,pos,kitchen,plot,events,service,appoint,estimation}'::text[], 'W', 'company_id'),
    ('invoices', '{accounting,counter,sales,purchase,inventory,employees,projects,site,manufacturing,pos,kitchen,plot,events,service,appoint,estimation}'::text[], 'W', 'company_id'),
    ('job_postings', '{recruitment,website}'::text[], 'M', 'company_id'),
    ('journal_entries', '{accounting,counter,sales,purchase,inventory,employees,projects,site,manufacturing,pos,kitchen,plot,events,service,appoint,estimation}'::text[], 'W', 'company_id'),
    ('journal_lines', '{accounting,counter,sales,purchase,inventory,employees,projects,site,manufacturing,pos,kitchen,plot,events,service,appoint,estimation}'::text[], 'W', 'company_id'),
    ('journals', '{accounting}'::text[], 'M', 'company_id'),
    ('labour_standards', '{kitchen,pos,employees}'::text[], 'M', 'company_id'),
    ('loyalty_accounts', '{kitchen,pos,sales}'::text[], 'W', 'company_id'),
    ('loyalty_programs', '{kitchen,pos,sales}'::text[], 'M', 'company_id'),
    ('loyalty_transactions', '{kitchen,pos,sales}'::text[], 'W', 'company_id'),
    ('maintenance_logs', '{manufacturing,service,site,kitchen}'::text[], 'W', 'company_id'),
    ('maintenance_schedules', '{manufacturing,service,site,kitchen}'::text[], 'M', 'company_id'),
    ('marketing_fund_entries', '{kitchen,pos}'::text[], 'W', 'company_id'),
    ('material_requisition_lines', '{purchase,projects,site,inventory,manufacturing}'::text[], 'W', 'company_id'),
    ('material_requisitions', '{purchase,projects,site,inventory,manufacturing}'::text[], 'W', 'company_id'),
    ('menu_items', '{kitchen,pos}'::text[], 'W', 'company_id'),
    ('menus', '{kitchen,pos}'::text[], 'M', 'company_id'),
    ('modifier_groups', '{kitchen,pos}'::text[], 'M', 'company_id'),
    ('modifiers', '{kitchen,pos}'::text[], 'W', 'company_id'),
    ('number_sequences', '{settings}'::text[], 'M', 'company_id'),
    ('package_types', '{inventory}'::text[], 'M', 'company_id'),
    ('panels', '{manufacturing,site,projects}'::text[], 'W', 'company_id'),
    ('partial_reconciles', '{accounting,counter,sales,purchase,inventory,employees,projects,site,manufacturing,pos,kitchen,plot,events,service,appoint,estimation}'::text[], 'W', 'company_id'),
    ('partner_bank_accounts', '{contacts,accounting,purchase,employees}'::text[], 'W', 'company_id'),
    ('partners', '{contacts,sales,crm,purchase,accounting,counter,plot,events,appoint,service,pos,kitchen,projects,site,recruitment,employees,estimation}'::text[], 'M', 'company_id'),
    ('payment_methods', '{counter,pos,kitchen,accounting}'::text[], 'M', 'company_id'),
    ('payment_terms', '{accounting}'::text[], 'M', 'company_id'),
    ('payments', '{accounting,counter,sales,purchase,inventory,employees,projects,site,manufacturing,pos,kitchen,plot,events,service,appoint,estimation}'::text[], 'W', 'company_id'),
    ('planning_shifts', '{employees,projects,site,kitchen,service}'::text[], 'W', 'company_id'),
    ('plant_equipment', '{site,projects,manufacturing}'::text[], 'M', 'company_id'),
    ('portal_access', '{plot,sales,settings,crm}'::text[], 'M', 'company_id'),
    ('pos_call_counters', '{kitchen,pos}'::text[], 'W', 'company_id'),
    ('pos_exceptions', '{kitchen,pos}'::text[], 'W', 'company_id'),
    ('pos_order_lines', '{kitchen,pos}'::text[], 'W', 'company_id'),
    ('pos_orders', '{kitchen,pos}'::text[], 'W', 'company_id'),
    ('pos_payments', '{kitchen,pos}'::text[], 'W', 'company_id'),
    ('pos_promotions', '{kitchen,pos}'::text[], 'M', 'company_id'),
    ('pos_reason_codes', '{kitchen,pos}'::text[], 'M', 'company_id'),
    ('pos_sessions', '{kitchen,pos}'::text[], 'W', 'company_id'),
    ('pos_vouchers', '{kitchen,pos}'::text[], 'W', 'company_id'),
    ('pricelist_items', '{sales,purchase,inventory,kitchen,pos}'::text[], 'W', 'company_id'),
    ('pricelists', '{sales,purchase,inventory,kitchen,pos}'::text[], 'M', 'company_id'),
    ('privacy_requests', '{settings}'::text[], 'W', 'company_id'),
    ('product_barcodes', '{inventory,sales,purchase,manufacturing,kitchen,pos,estimation,projects,site}'::text[], 'W', 'company_id'),
    ('product_categories', '{inventory,purchase,sales,kitchen}'::text[], 'M', 'company_id'),
    ('product_kit_components', '{inventory,sales,purchase,manufacturing,kitchen,pos,estimation,projects,site}'::text[], 'W', 'company_id'),
    ('product_modifier_groups', '{kitchen,pos}'::text[], 'W', 'company_id'),
    ('product_prices', '{inventory,sales,purchase,manufacturing,kitchen,pos,estimation,projects,site}'::text[], 'W', 'company_id'),
    ('product_supplier_prices', '{purchase,inventory,estimation}'::text[], 'W', 'company_id'),
    ('production_consumption', '{manufacturing,kitchen}'::text[], 'W', '(select r.company_id from public.production_runs r where r.id = run_id)'),
    ('production_runs', '{manufacturing,kitchen}'::text[], 'W', 'company_id'),
    ('products', '{inventory,sales,purchase,manufacturing,kitchen,pos,estimation,projects,site}'::text[], 'M', 'company_id'),
    ('project_boq', '{projects,site,estimation}'::text[], 'W', 'company_id'),
    ('project_budgets', '{projects,site,estimation}'::text[], 'W', 'company_id'),
    ('project_certificate_lines', '{projects,site}'::text[], 'W', 'company_id'),
    ('project_certificates', '{projects,site}'::text[], 'W', 'company_id'),
    ('project_items', '{projects,site,estimation,manufacturing,purchase}'::text[], 'W', 'company_id'),
    ('project_milestones', '{projects,site}'::text[], 'W', 'company_id'),
    ('project_stages', '{projects}'::text[], 'M', 'company_id'),
    ('project_tasks', '{projects,site,service,employees,crm,documents,plot}'::text[], 'W', 'company_id'),
    ('project_variations', '{projects,site}'::text[], 'W', 'company_id'),
    ('projects', '{projects,site,estimation,sales,plot}'::text[], 'M', 'company_id'),
    ('properties', '{plot}'::text[], 'M', 'company_id'),
    ('property_activity', '{plot}'::text[], 'W', 'company_id'),
    ('property_announcements', '{plot}'::text[], 'W', 'company_id'),
    ('property_bids', '{plot}'::text[], 'W', 'company_id'),
    ('property_budget_lines', '{plot}'::text[], 'W', 'company_id'),
    ('property_budgets', '{plot}'::text[], 'W', 'company_id'),
    ('property_charge_runs', '{plot}'::text[], 'W', 'company_id'),
    ('property_charges', '{plot}'::text[], 'W', 'company_id'),
    ('property_checkins', '{plot}'::text[], 'W', 'company_id'),
    ('property_checklist_items', '{plot}'::text[], 'W', 'company_id'),
    ('property_documents', '{plot}'::text[], 'W', 'company_id'),
    ('property_meeting_items', '{plot}'::text[], 'W', 'company_id'),
    ('property_meeting_votes', '{plot}'::text[], 'W', 'company_id'),
    ('property_meetings', '{plot}'::text[], 'W', 'company_id'),
    ('property_members', '{plot}'::text[], 'M', 'company_id'),
    ('property_notices', '{plot}'::text[], 'W', 'company_id'),
    ('property_ownerships', '{plot}'::text[], 'W', 'company_id'),
    ('property_projects', '{plot}'::text[], 'W', 'company_id'),
    ('property_residents', '{plot}'::text[], 'W', 'company_id'),
    ('property_resolutions', '{plot}'::text[], 'W', 'company_id'),
    ('property_suggestions', '{plot}'::text[], 'W', 'company_id'),
    ('property_tasks', '{plot}'::text[], 'W', 'company_id'),
    ('property_tenancies', '{plot}'::text[], 'W', 'company_id'),
    ('property_units', '{plot}'::text[], 'M', 'company_id'),
    ('purchase_order_lines', '{purchase,projects,site,manufacturing,inventory,events}'::text[], 'W', 'company_id'),
    ('purchase_orders', '{purchase,projects,site,manufacturing,inventory,events}'::text[], 'W', 'company_id'),
    ('putaway_rules', '{inventory}'::text[], 'M', 'company_id'),
    ('quote_template_lines', '{sales}'::text[], 'W', 'company_id'),
    ('quote_templates', '{sales}'::text[], 'M', 'company_id'),
    ('recurring_invoice_lines', '{accounting,sales}'::text[], 'W', 'company_id'),
    ('recurring_invoices', '{accounting,sales}'::text[], 'M', 'company_id'),
    ('regions', '{kitchen,pos,settings}'::text[], 'M', 'company_id'),
    ('reordering_rules', '{inventory,purchase}'::text[], 'W', 'company_id'),
    ('report_schedules', '{insights,accounting}'::text[], 'M', 'company_id'),
    ('reports', '{insights,accounting}'::text[], 'W', 'company_id'),
    ('reservations', '{kitchen,pos,events}'::text[], 'W', 'company_id'),
    ('retention_releases', '{projects,site,accounting}'::text[], 'W', 'company_id'),
    ('rfis', '{documents,projects,site}'::text[], 'W', 'company_id'),
    ('rfq_bids', '{purchase,projects,site,estimation}'::text[], 'W', 'company_id'),
    ('rfq_lines', '{purchase,projects,site,estimation}'::text[], 'W', 'company_id'),
    ('rfq_vendors', '{purchase,projects,site,estimation}'::text[], 'W', 'company_id'),
    ('rfqs', '{purchase,projects,site,estimation}'::text[], 'W', 'company_id'),
    ('roast_batches', '{kitchen,manufacturing}'::text[], 'W', 'company_id'),
    ('royalty_invoices', '{kitchen,pos,accounting}'::text[], 'W', 'company_id'),
    ('royalty_schemes', '{kitchen,pos}'::text[], 'M', 'company_id'),
    ('sale_order_lines', '{sales,crm,projects,site,service,events}'::text[], 'W', 'company_id'),
    ('sale_orders', '{sales,crm,projects,site,service,events}'::text[], 'W', 'company_id'),
    ('sales_channels', '{sales,kitchen,pos}'::text[], 'M', 'company_id'),
    ('sales_forecasts', '{sales,crm,kitchen,pos}'::text[], 'W', 'company_id'),
    ('sales_teams', '{sales,crm}'::text[], 'M', 'company_id'),
    ('schedule_tasks', '{projects,site}'::text[], 'W', 'company_id'),
    ('service_maintenance_plans', '{service}'::text[], 'M', 'company_id'),
    ('service_ticket_lines', '{service}'::text[], 'W', 'company_id'),
    ('service_tickets', '{service}'::text[], 'W', 'company_id'),
    ('service_warranties', '{service}'::text[], 'W', 'company_id'),
    ('shift_swaps', '{employees,kitchen}'::text[], 'W', 'company_id'),
    ('shift_templates', '{employees,kitchen}'::text[], 'M', 'company_id'),
    ('shipment_items', '{purchase,inventory}'::text[], 'W', 'company_id'),
    ('shipments', '{purchase,inventory}'::text[], 'W', 'company_id'),
    ('sign_requests', '{sign,documents,sales,employees,projects}'::text[], 'W', 'company_id'),
    ('sign_signatures', '{sign,documents,sales,employees,projects}'::text[], 'W', 'company_id'),
    ('site_diaries', '{site,projects}'::text[], 'W', 'company_id'),
    ('site_hostnames', '{website}'::text[], 'M', 'company_id'),
    ('site_incidents', '{site,projects}'::text[], 'W', 'company_id'),
    ('site_pages', '{website}'::text[], 'W', 'company_id'),
    ('site_submissions', '{website,crm}'::text[], 'W', 'company_id'),
    ('sites', '{website}'::text[], 'M', 'company_id'),
    ('skills', '{employees}'::text[], 'M', 'company_id'),
    ('snags', '{site,projects,plot}'::text[], 'W', 'company_id'),
    ('sprints', '{projects,site}'::text[], 'W', 'company_id'),
    ('standing_orders', '{kitchen,purchase}'::text[], 'W', 'company_id'),
    ('stock_count_lines', '{inventory,kitchen}'::text[], 'W', 'company_id'),
    ('stock_counts', '{inventory,kitchen}'::text[], 'W', 'company_id'),
    ('stock_locations', '{inventory}'::text[], 'M', 'company_id'),
    ('stock_lots', '{inventory,purchase,sales,manufacturing,projects,site,pos,kitchen,service}'::text[], 'W', 'company_id'),
    ('stock_move_lines', '{inventory,purchase,sales,manufacturing,projects,site,pos,kitchen,service}'::text[], 'W', 'company_id'),
    ('stock_moves', '{inventory,purchase,sales,manufacturing,projects,site,pos,kitchen,service}'::text[], 'W', 'company_id'),
    ('stock_pickings', '{inventory,purchase,sales}'::text[], 'W', 'company_id'),
    ('stock_reservations', '{inventory,purchase,projects,site,manufacturing}'::text[], 'W', 'company_id'),
    ('stock_transfer_lines', '{inventory,kitchen}'::text[], 'W', 'company_id'),
    ('stock_transfers', '{inventory,kitchen}'::text[], 'W', 'company_id'),
    ('stock_valuation_layers', '{inventory,purchase,sales,manufacturing,projects,site,pos,kitchen,service}'::text[], 'W', 'company_id'),
    ('storage_categories', '{inventory}'::text[], 'M', 'company_id'),
    ('store_access', '{kitchen,pos,settings}'::text[], 'M', 'company_id'),
    ('store_audits', '{kitchen,pos}'::text[], 'W', 'company_id'),
    ('store_item_availability', '{kitchen,pos}'::text[], 'W', 'company_id'),
    ('store_tables', '{kitchen,pos}'::text[], 'M', 'company_id'),
    ('stored_value_accounts', '{kitchen,pos,sales}'::text[], 'W', 'company_id'),
    ('stored_value_transactions', '{kitchen,pos,sales}'::text[], 'W', 'company_id'),
    ('stores', '{kitchen,pos}'::text[], 'M', 'company_id'),
    ('subcontract_certificates', '{projects,site,purchase}'::text[], 'W', 'company_id'),
    ('subcontracts', '{projects,site,purchase}'::text[], 'W', 'company_id'),
    ('submittals', '{documents,projects,site}'::text[], 'W', 'company_id'),
    ('subscription_plans', '{kitchen,pos,sales}'::text[], 'M', 'company_id'),
    ('subscription_redemptions', '{kitchen,pos,sales}'::text[], 'W', 'company_id'),
    ('subscriptions', '{kitchen,pos,sales}'::text[], 'W', 'company_id'),
    ('task_activity', '{projects,site,service,employees,crm,documents,plot}'::text[], 'W', 'company_id'),
    ('task_checklists', '{projects,site,service,employees,crm,documents,plot}'::text[], 'W', 'company_id'),
    ('task_comments', '{projects,site,service,employees,crm,documents,plot}'::text[], 'W', 'company_id'),
    ('task_labels', '{projects}'::text[], 'M', 'company_id'),
    ('task_stages', '{projects}'::text[], 'M', 'company_id'),
    ('task_watchers', '{projects,site,service,employees,crm,documents,plot}'::text[], 'W', 'company_id'),
    ('taxes', '{accounting}'::text[], 'M', 'company_id'),
    ('tender_lines', '{estimation,sales}'::text[], 'W', 'company_id'),
    ('tenders', '{estimation,sales}'::text[], 'W', 'company_id'),
    ('term_overrides', '{settings}'::text[], 'M', 'company_id'),
    ('timesheets', '{projects,site,service,employees}'::text[], 'W', 'company_id'),
    ('tip_allocations', '{kitchen,pos,employees}'::text[], 'W', 'company_id'),
    ('tip_pools', '{kitchen,pos,employees}'::text[], 'W', 'company_id'),
    ('tool_movements', '{manufacturing,site}'::text[], 'W', '(select t.company_id from public.tools t where t.id = tool_id)'),
    ('tools', '{manufacturing,site}'::text[], 'M', 'company_id'),
    ('trace_seals', '{accounting,purchase,inventory}'::text[], 'W', 'company_id'),
    ('training_bookings', '{employees}'::text[], 'W', 'company_id'),
    ('training_courses', '{employees}'::text[], 'M', 'company_id'),
    ('transmittal_items', '{documents,projects,site}'::text[], 'W', 'company_id'),
    ('transmittals', '{documents,projects,site}'::text[], 'W', 'company_id'),
    ('uoms', '{inventory,purchase,sales,kitchen,pos,manufacturing}'::text[], 'M', 'company_id'),
    ('user_company_access', '{settings}'::text[], 'M', 'company_id'),
    ('warehouses', '{inventory}'::text[], 'M', 'company_id'),
    ('waste_entries', '{kitchen,pos,inventory}'::text[], 'W', 'company_id'),
    ('waste_reasons', '{kitchen,pos,inventory}'::text[], 'M', 'company_id'),
    ('wholesale_accounts', '{kitchen,pos,sales}'::text[], 'W', 'company_id'),
    ('work_order_operations', '{manufacturing}'::text[], 'W', 'company_id'),
    ('work_orders', '{manufacturing,site,projects}'::text[], 'W', 'company_id')
  ) as v(tbl, mods, del, cexpr) loop
    execute format('drop policy if exists rg_ins on public.%I', g.tbl);
    execute format('drop policy if exists rg_upd on public.%I', g.tbl);
    execute format('drop policy if exists rg_del on public.%I', g.tbl);
    if g.tbl not in ('companies', 'backups') then
      execute format('create policy rg_ins on public.%I as restrictive for insert to authenticated with check (public.can_write_app(%s, %L::text[]))',
                     g.tbl, g.cexpr, g.mods);
    end if;
    if g.tbl <> 'backups' then
      execute format('create policy rg_upd on public.%I as restrictive for update to authenticated using (public.can_write_app(%s, %L::text[])) with check (public.can_write_app(%s, %L::text[]))',
                     g.tbl, g.cexpr, g.mods, g.cexpr, g.mods);
    end if;
    if g.tbl <> 'companies' then
      fn := case when g.del = 'M' then 'can_manage_app' else 'can_write_app' end;
      execute format('create policy rg_del on public.%I as restrictive for delete to authenticated using (public.%s(%s, %L::text[]))',
                     g.tbl, fn, g.cexpr, g.mods);
    end if;
  end loop;
end $gates$;

-- salaries are read by roles that see salaries, and by the person they belong to
drop policy if exists rg_salaries on public.hr_contracts;
create policy rg_salaries on public.hr_contracts as restrictive for select to authenticated
  using (public.can_see(company_id, 'salaries') or employee_id = public.my_employee_id(company_id));
drop policy if exists rg_salaries on public.hr_payslips;
create policy rg_salaries on public.hr_payslips as restrictive for select to authenticated
  using (public.can_see(company_id, 'salaries') or employee_id = public.my_employee_id(company_id));
drop policy if exists rg_salaries on public.hr_payslip_lines;
create policy rg_salaries on public.hr_payslip_lines as restrictive for select to authenticated
  using (public.can_see(company_id, 'salaries')
         or exists (select 1 from public.hr_payslips s where s.id = payslip_id and s.employee_id = public.my_employee_id(company_id)));
drop policy if exists rg_salaries on public.hr_payslip_runs;
create policy rg_salaries on public.hr_payslip_runs as restrictive for select to authenticated
  using (public.can_see(company_id, 'salaries'));
